### ISSUE TITLE
No Java file only smali

### ISSUE THREAD

**Issue by Neolex-Security** [ThisIsLibra/AndroidProjectCreator#10]
Hello,
Is it normal that I don't have any java file in the android studio project created ?
I have just the smali files and the manifest but no decompiled java files .

**Comment by ThisIsLibra** [comment]
Hello Neolex,

The fact that you have no decompiled code is indeed not how the program is supposed to work, which can be caused by two things:
1. The installation of the used decompiler failed, and thus cannot be used
2. The decompiler crashed during the decompilation process

Make sure you have all tools installed correctly and review the output of the logs that are produced during the decompilation process.

Please note that I cannot help you further without details. If you do not provide more details, the issue will be closed.

**Comment by Neolex-Security** [comment]
Hello,
sorry yes it was the decompiler crashing during the decompilation so I used jadx  which doesn't crash.
Sorry to make you waste your time !
Have a good days
