### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by dfdfdfs** [ThisIsLibra/AndroidProjectCreator#18]
Hi tried two commands. java  -jar AndroidProjectCreator.jar -compactInstall  and 
java  -jar AndroidProjectCreator.jar -Install

Error 

D:\TEST4>java  -jar AndroidProjectCreator.jar -compactInstall
[+]AndroidProjectCreator 1.5-stable [developed by Max 'Libra' Kersten <info@maxkersten.nl> or @Libranalysis on Twitter]

[+]Starting the installation
[+]Starting cloning the repositories
[+]Started cloning CompactInstall version 1.1 (dated 11-05-2021)

[+]An error has occurred, therefore AndroidProjectCreator has shut down. The error message is given below.

[+]There was an error cloing CompactInstall version 1.1 (dated 11-05-2021). Verify your internet connection and the permissions of the folder!

[+]For additional details, see the stack traces of the used tools above.

D:\TEST4>

D:\TEST4>java  -jar AndroidProjectCreator.jar -install
[+]AndroidProjectCreator 1.5-stable [developed by Max 'Libra' Kersten <info@maxkersten.nl> or @Libranalysis on Twitter]

[+]Starting the installation
[+]Starting cloning the repositories
[+]Started cloning androidproject

[+]An error has occurred, therefore AndroidProjectCreator has shut down. The error message is given below.

[+]There was an error cloing androidproject. Verify your internet connection and the permissions of the folder!

[+]For additional details, see the stack traces of the used tools above.

D:\TEST4>
There are no problems with the Internet. Can you upload the full jar file?

**Comment by ThisIsLibra** [comment]
Hello,

Thank you for submitting the issue. You seem to be using the latest version of APC, although I dont know what Java version you are using. The Git related actions could fail due to a Java version mismatch, although I think this is very unlikely. Per your own statement, you have no internet issues, but did you check the folder related permissions as the error message states?

To verify, I just git cloned the repository and installed the compact installation without any issues, as can be seen below. As such, I think the error is likely in your folder structure, and/or in another part of your set-up. With the lack of details, I cannot provide more help than this.

![image](https://user-images.githubusercontent.com/26792445/143028830-6b014e0e-e065-48f1-ace8-8152531fb647.png)

**Comment by ThisIsLibra** [comment]
Due to the fact that I cannot replicate this issue, and there has been no comment on here for the last 14 days, I will now close this issue.
