### ISSUE TITLE
learn how to git and make a proper release

### ISSUE THREAD

**Issue by blshkv** [ThisIsLibra/AndroidProjectCreator#4]
the ```target``` directory need to be gone, the jar need to be under ```release``` tab 
and so on.

**Comment by ThisIsLibra** [comment]
Hello Anton,

First off, I'd like to express my thanks for reaching out to me. I do think, however, that a different approach would've been more helpful. An in-depth guide (in numerous languages) on how to improve on asking questions can be found [here](http://www.catb.org/~esr/faqs/smart-questions.html).

To address the issue at hand, I'll state that the page on my website contains all the required information and is therefore referenced within the read me file of this repository. Github is used to host the code with some versioning system in it. I specifically use the target folder, since it is easier to use. If you feel like it can improve, you can [create a pull request](https://help.github.com/en/articles/creating-a-pull-request) with proposed changes. I'm looking forward to your proposed changes and I'm sure that we can make APC even better together!

**Comment by blshkv** [comment]
Thank you for your patient reply. The problem with the current approach is that many distros won't be able to monitor your project and won't be able to pickup a new version in time. It also means that packaging of your software will be different, i.e. they would need to spend extra time to attach a release to a commit in a custom build.

This is has nothing to do with code change, so I'm unable to neither create a pull request.

The basic usage of githib is covered here:
https://help.github.com/en/articles/creating-releases

Feel free to close this issue if you are not ready for "traditional" usage.

**Comment by ThisIsLibra** [comment]
Thank you for the explanation and link. I've added a release and will do so when I update it in the future. The target folder is cleaned, which was possible via a pull request.

I think your ideas are good, but the way you put them at first aren't really the way to go, which is something for you to look at. The software I publish here is created by me in my spare time. I publish everything for free, and as such I don't think that the attitude you first had is considered decent. Even if you paid for it, the attitude would be one that is often referred to as 'entitled'.

I'll hereby close the issue as all points have been addressed.

**Comment by blshkv** [comment]
Well, we are in the same boat. I report bugs in my spare time and not always ready to write detailed explanation about basic principles. However, i re-read the subject and found it root too... My apologies!

Thank you for the switch! I have received a notification about a new release!
